apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coder-ns-rb
subjects:
- kind: ServiceAccount
  name: coder
  namespace: hosted
roleRef:
  kind: ClusterRole
  name: coder-ns
  apiGroup: rbac.authorization.k8s.io