apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coder-ns
rules:
- apiGroups: ["*"]
  resources: ["ingresses", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]